// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9-hVS_E4iyBDWwh8GILjXx-s7e1iz5w4',
    appId: '1:413172237624:web:ae504ab371ae232d3f6dcd',
    messagingSenderId: '413172237624',
    projectId: 'edarshop-d20aa',
    authDomain: 'edarshop-d20aa.firebaseapp.com',
    storageBucket: 'edarshop-d20aa.firebasestorage.app',
    measurementId: 'G-76VBK4FFZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwfshXARVpcl1772J2O6NnU0rpIFYIhvY',
    appId: '1:413172237624:android:3db1529054dd1d213f6dcd',
    messagingSenderId: '413172237624',
    projectId: 'edarshop-d20aa',
    storageBucket: 'edarshop-d20aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz7L4y30qy73NVk-W9MC2F_69mpglY9Ac',
    appId: '1:413172237624:ios:44195046ba1ac9b93f6dcd',
    messagingSenderId: '413172237624',
    projectId: 'edarshop-d20aa',
    storageBucket: 'edarshop-d20aa.firebasestorage.app',
    iosBundleId: 'com.example.edarShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz7L4y30qy73NVk-W9MC2F_69mpglY9Ac',
    appId: '1:413172237624:ios:44195046ba1ac9b93f6dcd',
    messagingSenderId: '413172237624',
    projectId: 'edarshop-d20aa',
    storageBucket: 'edarshop-d20aa.firebasestorage.app',
    iosBundleId: 'com.example.edarShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9-hVS_E4iyBDWwh8GILjXx-s7e1iz5w4',
    appId: '1:413172237624:web:2ca07d9c62aeaa453f6dcd',
    messagingSenderId: '413172237624',
    projectId: 'edarshop-d20aa',
    authDomain: 'edarshop-d20aa.firebaseapp.com',
    storageBucket: 'edarshop-d20aa.firebasestorage.app',
    measurementId: 'G-JL6R64E66C',
  );

}